export { default as userMock } from './user.mock.json'
export { default as authMock } from './auth.mock.json'
export { default as educationalStageMock } from './educationalStage.mock.json'
export { default as profilesMock } from './profiles.mock.json'
export { default as prepareAccessProfileMock } from './prepareAccess.profile.mock.json'
