steps:
  - task: NodeTool@0
    displayName: Installing node 14+
    inputs:
      versionSpec: 14.x

  - task: Cache@2
    inputs:
      path: $(YARN_CACHE_FOLDER)
      key: '"yarn" | "$(Agent.OS)" | yarn.lock'
      restoreKeys: |
        yarn | "$(Agent.OS)"
        yarn
    displayName: Cache Yarn packages

  # - script: yarn --frozen-lockfile
  #   displayName: Installing project dependencies
  - script: yarn
    displayName: Installing project dependencies
