const professorMedio = [
  {
    id: 0,
    title: 'Avaliação',
    cards: [
      {
        id: 0,
        title: 'Guia de Estudo',
        description: 'Lista de exercícios pronta do Guia de Estudos na Studos',
        notification: '2',
        url:
          'https://plus-app.studos.com.br/auth?accessKey=4e1e0a26-b495-11ea-b3de-0242ac130004&accessToken=iweSkoEjepTnXPdFo5DIQLgKZbkIbhNQEiZnJuaOdeY%3D',
        color: '#3F51B5',
        icon: 'cards/avaliacao-1.svg',
        iframe: true,
      },
      {
        id: 1,
        title: 'Avaliações',
        description: 'Ferramenta de criação de avaliações na Studos',
        notification: '1',
        url: '#!',
        color: '#3F51B5',
        icon: 'cards/avaliacao-2.svg',
      },
      {
        id: 2,
        title: 'Simulados',
        description: 'Simulados Enem, Fuvest e outros vestibulares do país',
        url: '#!',
        color: '#3F51B5',
        icon: 'cards/avaliacao-3.svg',
      },
      {
        id: 3,
        title: 'Atividades',
        description: 'Ferramenta para envio e correção de atividades',
        url: '#!',
        color: '#3F51B5',
        icon: 'cards/avaliacao-4.svg',
      },
      {
        id: 4,
        title: 'Relatórios',
        description: 'Relatórios de atividades e avaliações',
        url: '#!',
        color: '#3F51B5',
        icon: 'cards/avaliacao-5.svg',
      },
      {
        id: 5,
        title: 'Redação',
        description: 'Ferramenta de redação na Studos',
        url: '#!',
        color: '#3F51B5',
        icon: 'cards/avaliacao-6.svg',
      },
    ],
  },
  {
    id: 1,
    title: 'Conteúdo',
    cards: [
      {
        id: 0,
        title: 'Livro Digital',
        description: 'Conteúdo digital interativo do Ensino Fundamental 1',
        url: '#!',
        color: '#673AB7',
        icon: 'cards/conteudo-1.svg',
      },
      {
        id: 2,
        title: 'Vídeo Aulas',
        description: 'Vídeo aulas semanais para alunos e professores',
        url: '#!',
        color: '#673AB7',
        icon: 'cards/conteudo-3.svg',
      },
      {
        id: 3,
        title: 'Compêndio 1ª Série Novo EM 2021',
        description: 'Degustação sobre o Novo Ensino Médio',
        url: '#!',
        color: '#673AB7',
        icon: 'cards/conteudo-4.svg',
      },
      {
        id: 4,
        title: 'Programação de Conteúdos',
        description: 'Sugestão de planejamento de conteúdo',
        url: '#!',
        color: '#673AB7',
        icon: 'cards/conteudo-5.svg',
      },
      {
        id: 5,
        title: 'Árvore Livros',
        description: 'Biblioteca de livros paradidáticos e romances',
        url: '#!',
        color: '#673AB7',
        icon: 'cards/conteudo-6.svg',
      },
    ],
  },
  {
    id: 2,
    title: 'Recursos',
    cards: [
      {
        id: 0,
        title: 'Plano Semanal',
        description:
          'Divisão do conteúdo em semanas e sugestões de conteúdos para alunos',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-1.svg',
      },
      {
        id: 1,
        title: 'Salas Virtuais',
        description: 'Ambiente para aulas online ao vivo',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-2.svg',
      },
      {
        id: 3,
        title: 'Word',
        description: 'Ferramenta de criação e edição de textos da Microsoft.',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-4.svg',
      },
      {
        id: 4,
        title: 'Excel',
        description:
          'Ferramenta de criação e edição de planilhas da Microsoft.',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-5.svg',
      },
      {
        id: 5,
        title: 'Power Point',
        description:
          'Ferramenta de criação e edição de slides de apresentação da Microsoft',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-6.svg',
      },
    ],
  },
  {
    id: 3,
    title: 'Comunicação',
    cards: [
      {
        id: 0,
        title: 'Mensagens',
        description: 'Ferramenta de mensagens entre professores, pais e alunos',
        url: '#!',
        color: '#03A9F4',
        icon: 'cards/comunicacao-1.svg',
      },
      {
        id: 1,
        title: 'Agenda',
        description: 'Agenda de eventos para a escola e professores',
        url: '#!',
        color: '#03A9F4',
        icon: 'cards/comunicacao-2.svg',
      },
      {
        id: 3,
        title: 'Revista SPE',
        description: 'Novidades do Sistema Positivo de Ensino',
        url: '#!',
        color: '#03A9F4',
        icon: 'cards/comunicacao-4.svg',
      },
      {
        id: 4,
        title: 'Blog da Assessoria',
        description: 'Página de comunicação da Assessoria Pedagógica',
        url: '#!',
        color: '#03A9F4',
        icon: 'cards/comunicacao-5.svg',
      },
    ],
  },
  {
    id: 4,
    title: 'Formação',
    cards: [
      {
        id: 0,
        title: 'Programa de Cursos 2020',
        description: 'Plataforma de formação continuada para professores',
        url: '#!',
        color: '#00BCD4',
        icon: 'cards/formacao-1.svg',
      },
      {
        id: 1,
        title: 'Proposta Pedagógica',
        description: 'Guias e documentos de apoio ao professor',
        url: '#!',
        color: '#00BCD4',
        icon: 'cards/formacao-2.svg',
      },
    ],
  },
];

const professorEF2 = [
  {
    id: 0,
    title: 'Avaliação',
    cards: [
      {
        id: 0,
        title: 'Guia de Estudo',
        description: 'Lista de exercícios pronta do Guia de Estudos na Studos',
        notification: '2',
        url:
          'https://plus-app.studos.com.br/auth?accessKey=4e1e0a26-b495-11ea-b3de-0242ac130004&accessToken=iweSkoEjepTnXPdFo5DIQLgKZbkIbhNQEiZnJuaOdeY%3D',
        color: '#3F51B5',
        icon: 'cards/avaliacao-1.svg',
        iframe: true,
      },
      {
        id: 1,
        title: 'Avaliações',
        description: 'Ferramenta de criação de avaliações na Studos',
        notification: '1',
        url: '#!',
        color: '#3F51B5',
        icon: 'cards/avaliacao-2.svg',
      },
      {
        id: 3,
        title: 'Atividades',
        description: 'Ferramenta para envio e correção de atividades',
        url: '#!',
        color: '#3F51B5',
        icon: 'cards/avaliacao-4.svg',
      },
      {
        id: 4,
        title: 'Relatórios',
        description: 'Relatórios de atividades e avaliações',
        url: '#!',
        color: '#3F51B5',
        icon: 'cards/avaliacao-5.svg',
      },
      {
        id: 5,
        title: 'Redação',
        description: 'Ferramenta de redação na Studos',
        url: '#!',
        color: '#3F51B5',
        icon: 'cards/avaliacao-6.svg',
      },
    ],
  },
  {
    id: 1,
    title: 'Conteúdo',
    cards: [
      {
        id: 0,
        title: 'Livro Digital',
        description: 'Conteúdo digital interativo do Ensino Fundamental 1',
        url: '#!',
        color: '#673AB7',
        icon: 'cards/conteudo-1.svg',
      },
      {
        id: 2,
        title: 'Vídeo Aulas',
        description: 'Vídeo aulas semanais para alunos e professores',
        url: '#!',
        color: '#673AB7',
        icon: 'cards/conteudo-3.svg',
      },
      {
        id: 4,
        title: 'Programação de Conteúdos',
        description: 'Sugestão de planejamento de conteúdo',
        url: '#!',
        color: '#673AB7',
        icon: 'cards/conteudo-5.svg',
      },
      {
        id: 5,
        title: 'Árvore Livros',
        description: 'Biblioteca de livros paradidáticos e romances',
        url: '#!',
        color: '#673AB7',
        icon: 'cards/conteudo-6.svg',
      },
    ],
  },
  {
    id: 2,
    title: 'Recursos',
    cards: [
      {
        id: 0,
        title: 'Plano Semanal',
        description:
          'Divisão do conteúdo em semanas e sugestões de conteúdos para alunos',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-1.svg',
      },
      {
        id: 1,
        title: 'Salas Virtuais',
        description: 'Ambiente para aulas online ao vivo',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-2.svg',
      },
      {
        id: 2,
        title: 'Playground',
        description: 'Jogos e Objetos Educacionais para a Educação Infantil',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-3.svg',
      },
      {
        id: 3,
        title: 'Word',
        description: 'Ferramenta de criação e edição de textos da Microsoft.',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-4.svg',
      },
      {
        id: 4,
        title: 'Excel',
        description:
          'Ferramenta de criação e edição de planilhas da Microsoft.',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-5.svg',
      },
      {
        id: 5,
        title: 'Power Point',
        description:
          'Ferramenta de criação e edição de slides de apresentação da Microsoft',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-6.svg',
      },
    ],
  },
  {
    id: 3,
    title: 'Comunicação',
    cards: [
      {
        id: 0,
        title: 'Mensagens',
        description: 'Ferramenta de mensagens entre professores, pais e alunos',
        url: '#!',
        color: '#03A9F4',
        icon: 'cards/comunicacao-1.svg',
      },
      {
        id: 1,
        title: 'Agenda',
        description: 'Agenda de eventos para a escola e professores',
        url: '#!',
        color: '#03A9F4',
        icon: 'cards/comunicacao-2.svg',
      },
      {
        id: 3,
        title: 'Revista SPE',
        description: 'Novidades do Sistema Positivo de Ensino',
        url: '#!',
        color: '#03A9F4',
        icon: 'cards/comunicacao-4.svg',
      },
      {
        id: 4,
        title: 'Blog da Assessoria',
        description: 'Página de comunicação da Assessoria Pedagógica',
        url: '#!',
        color: '#03A9F4',
        icon: 'cards/comunicacao-5.svg',
      },
    ],
  },
  {
    id: 4,
    title: 'Formação',
    cards: [
      {
        id: 0,
        title: 'Programa de Cursos 2020',
        description: 'Plataforma de formação continuada para professores',
        url: '#!',
        color: '#00BCD4',
        icon: 'cards/formacao-1.svg',
      },
      {
        id: 1,
        title: 'Proposta Pedagógica',
        description: 'Guias e documentos de apoio ao professor',
        url: '#!',
        color: '#00BCD4',
        icon: 'cards/formacao-2.svg',
      },
    ],
  },
];

const professorEF1 = [
  {
    id: 0,
    title: 'Avaliação',
    cards: [
      {
        id: 0,
        title: 'Guia de Estudo',
        description: 'Lista de exercícios pronta do Guia de Estudos na Studos',
        notification: '2',
        url:
          'https://plus-app.studos.com.br/auth?accessKey=4e1e0a26-b495-11ea-b3de-0242ac130004&accessToken=iweSkoEjepTnXPdFo5DIQLgKZbkIbhNQEiZnJuaOdeY%3D',
        color: '#3F51B5',
        icon: 'cards/avaliacao-1.svg',
        iframe: true,
      },
      {
        id: 1,
        title: 'Avaliações',
        description: 'Ferramenta de criação de avaliações na Studos',
        notification: '1',
        url: '#!',
        color: '#3F51B5',
        icon: 'cards/avaliacao-2.svg',
      },
      {
        id: 3,
        title: 'Atividades',
        description: 'Ferramenta para envio e correção de atividades',
        url: '#!',
        color: '#3F51B5',
        icon: 'cards/avaliacao-4.svg',
      },
      {
        id: 4,
        title: 'Relatórios',
        description: 'Relatórios de atividades e avaliações',
        url: '#!',
        color: '#3F51B5',
        icon: 'cards/avaliacao-5.svg',
      },
      {
        id: 5,
        title: 'Redação',
        description: 'Ferramenta de redação na Studos',
        url: '#!',
        color: '#3F51B5',
        icon: 'cards/avaliacao-6.svg',
      },
    ],
  },
  {
    id: 1,
    title: 'Conteúdo',
    cards: [
      {
        id: 0,
        title: 'Livro Digital',
        description: 'Conteúdo digital interativo do Ensino Fundamental 1',
        url: '#!',
        color: '#673AB7',
        icon: 'cards/conteudo-1.svg',
      },
      {
        id: 2,
        title: 'Vídeo Aulas',
        description: 'Vídeo aulas semanais para alunos e professores',
        url: '#!',
        color: '#673AB7',
        icon: 'cards/conteudo-3.svg',
      },
      {
        id: 4,
        title: 'Programação de Conteúdos',
        description: 'Sugestão de planejamento de conteúdo',
        url: '#!',
        color: '#673AB7',
        icon: 'cards/conteudo-5.svg',
      },
      {
        id: 5,
        title: 'Árvore Livros',
        description: 'Biblioteca de livros paradidáticos e romances',
        url: '#!',
        color: '#673AB7',
        icon: 'cards/conteudo-6.svg',
      },
    ],
  },
  {
    id: 2,
    title: 'Recursos',
    cards: [
      {
        id: 0,
        title: 'Plano Semanal',
        description:
          'Divisão do conteúdo em semanas e sugestões de conteúdos para alunos',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-1.svg',
      },
      {
        id: 1,
        title: 'Salas Virtuais',
        description: 'Ambiente para aulas online ao vivo',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-2.svg',
      },
      {
        id: 2,
        title: 'Playground',
        description: 'Jogos e Objetos Educacionais para a Educação Infantil',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-3.svg',
      },
      {
        id: 3,
        title: 'Word',
        description: 'Ferramenta de criação e edição de textos da Microsoft.',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-4.svg',
      },
      {
        id: 4,
        title: 'Excel',
        description:
          'Ferramenta de criação e edição de planilhas da Microsoft.',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-5.svg',
      },
      {
        id: 5,
        title: 'Power Point',
        description:
          'Ferramenta de criação e edição de slides de apresentação da Microsoft',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-6.svg',
      },
    ],
  },
  {
    id: 3,
    title: 'Comunicação',
    cards: [
      {
        id: 0,
        title: 'Mensagens',
        description: 'Ferramenta de mensagens entre professores, pais e alunos',
        url: '#!',
        color: '#03A9F4',
        icon: 'cards/comunicacao-1.svg',
      },
      {
        id: 1,
        title: 'Agenda',
        description: 'Agenda de eventos para a escola e professores',
        url: '#!',
        color: '#03A9F4',
        icon: 'cards/comunicacao-2.svg',
      },
      {
        id: 3,
        title: 'Revista SPE',
        description: 'Novidades do Sistema Positivo de Ensino',
        url: '#!',
        color: '#03A9F4',
        icon: 'cards/comunicacao-4.svg',
      },
      {
        id: 4,
        title: 'Blog da Assessoria',
        description: 'Página de comunicação da Assessoria Pedagógica',
        url: '#!',
        color: '#03A9F4',
        icon: 'cards/comunicacao-5.svg',
      },
    ],
  },
  {
    id: 4,
    title: 'Formação',
    cards: [
      {
        id: 0,
        title: 'Programa de Cursos 2020',
        description: 'Plataforma de formação continuada para professores',
        url: '#!',
        color: '#00BCD4',
        icon: 'cards/formacao-1.svg',
      },
      {
        id: 1,
        title: 'Proposta Pedagógica',
        description: 'Guias e documentos de apoio ao professor',
        url: '#!',
        color: '#00BCD4',
        icon: 'cards/formacao-2.svg',
      },
    ],
  },
];

const professorInfantil = [
  {
    id: 0,
    title: 'Avaliação',
    cards: [
      {
        id: 3,
        title: 'Atividades',
        description: 'Ferramenta para envio e correção de atividades',
        url: '#!',
        color: '#3F51B5',
        icon: 'cards/avaliacao-4.svg',
      },
      {
        id: 4,
        title: 'Relatórios',
        description: 'Relatórios de atividades e avaliações',
        url: '#!',
        color: '#3F51B5',
        icon: 'cards/avaliacao-5.svg',
      },
      {
        id: 5,
        title: 'Redação',
        description: 'Ferramenta de redação na Studos',
        url: '#!',
        color: '#3F51B5',
        icon: 'cards/avaliacao-6.svg',
      },
    ],
  },
  {
    id: 1,
    title: 'Conteúdo',
    cards: [
      {
        id: 0,
        title: 'Livro Digital',
        description: 'Conteúdo digital interativo do Ensino Fundamental 1',
        url: '#!',
        color: '#673AB7',
        icon: 'cards/conteudo-1.svg',
      },
      {
        id: 4,
        title: 'Programação de Conteúdos',
        description: 'Sugestão de planejamento de conteúdo',
        url: '#!',
        color: '#673AB7',
        icon: 'cards/conteudo-5.svg',
      },
      {
        id: 5,
        title: 'Árvore Livros',
        description: 'Biblioteca de livros paradidáticos e romances',
        url: '#!',
        color: '#673AB7',
        icon: 'cards/conteudo-6.svg',
      },
    ],
  },
  {
    id: 2,
    title: 'Recursos',
    cards: [
      {
        id: 0,
        title: 'Plano Semanal',
        description:
          'Divisão do conteúdo em semanas e sugestões de conteúdos para alunos',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-1.svg',
      },
      {
        id: 1,
        title: 'Salas Virtuais',
        description: 'Ambiente para aulas online ao vivo',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-2.svg',
      },
      {
        id: 3,
        title: 'Word',
        description: 'Ferramenta de criação e edição de textos da Microsoft.',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-4.svg',
      },
      {
        id: 4,
        title: 'Excel',
        description:
          'Ferramenta de criação e edição de planilhas da Microsoft.',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-5.svg',
      },
      {
        id: 5,
        title: 'Power Point',
        description:
          'Ferramenta de criação e edição de slides de apresentação da Microsoft',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-6.svg',
      },
    ],
  },
  {
    id: 3,
    title: 'Comunicação',
    cards: [
      {
        id: 0,
        title: 'Mensagens',
        description: 'Ferramenta de mensagens entre professores, pais e alunos',
        url: '#!',
        color: '#03A9F4',
        icon: 'cards/comunicacao-1.svg',
      },
      {
        id: 1,
        title: 'Agenda',
        description: 'Agenda de eventos para a escola e professores',
        url: '#!',
        color: '#03A9F4',
        icon: 'cards/comunicacao-2.svg',
      },
      {
        id: 2,
        title: 'Diário',
        description:
          'Ferramenta de comunicação entre escola e pais da Educação Infantil',
        url: '#!',
        color: '#03A9F4',
        icon: 'cards/comunicacao-3.svg',
      },
      {
        id: 3,
        title: 'Revista SPE',
        description: 'Novidades do Sistema Positivo de Ensino',
        url: '#!',
        color: '#03A9F4',
        icon: 'cards/comunicacao-4.svg',
      },
      {
        id: 4,
        title: 'Blog da Assessoria',
        description: 'Página de comunicação da Assessoria Pedagógica',
        url: '#!',
        color: '#03A9F4',
        icon: 'cards/comunicacao-5.svg',
      },
    ],
  },
  {
    id: 4,
    title: 'Formação',
    cards: [
      {
        id: 0,
        title: 'Programa de Cursos 2020',
        description: 'Plataforma de formação continuada para professores',
        url: '#!',
        color: '#00BCD4',
        icon: 'cards/formacao-1.svg',
      },
      {
        id: 1,
        title: 'Proposta Pedagógica',
        description: 'Guias e documentos de apoio ao professor',
        url: '#!',
        color: '#00BCD4',
        icon: 'cards/formacao-2.svg',
      },
    ],
  },
];

const aluno = [
  {
    id: 0,
    title: 'Avaliação',
    cards: [
      {
        id: 0,
        title: 'Guia de Estudo',
        description: 'Lista de exercícios pronta do Guia de Estudos na Studos',
        notification: '2',
        url:
          'https://plus-app.studos.com.br/auth?accessKey=4e1e0a26-b495-11ea-b3de-0242ac130004&accessToken=iweSkoEjepTnXPdFo5DIQLgKZbkIbhNQEiZnJuaOdeY%3D',
        color: '#3F51B5',
        icon: 'cards/avaliacao-1.svg',
        iframe: true,
      },
      {
        id: 1,
        title: 'Avaliações',
        description: 'Ferramenta de criação de avaliações na Studos',
        notification: '1',
        url: '#!',
        color: '#3F51B5',
        icon: 'cards/avaliacao-2.svg',
      },
      {
        id: 3,
        title: 'Atividades',
        description: 'Ferramenta para envio e correção de atividades',
        url: '#!',
        color: '#3F51B5',
        icon: 'cards/avaliacao-4.svg',
      },
      {
        id: 4,
        title: 'Relatórios',
        description: 'Relatórios de atividades e avaliações',
        url: '#!',
        color: '#3F51B5',
        icon: 'cards/avaliacao-5.svg',
      },
      {
        id: 5,
        title: 'Redação',
        description: 'Ferramenta de redação na Studos',
        url: '#!',
        color: '#3F51B5',
        icon: 'cards/avaliacao-6.svg',
      },
    ],
  },
  {
    id: 1,
    title: 'Conteúdo',
    cards: [
      {
        id: 0,
        title: 'Livro Digital',
        description: 'Conteúdo digital interativo do Ensino Fundamental 1',
        url: '#!',
        color: '#673AB7',
        icon: 'cards/conteudo-1.svg',
      },
      {
        id: 2,
        title: 'Vídeo Aulas',
        description: 'Vídeo aulas semanais para alunos e professores',
        url: '#!',
        color: '#673AB7',
        icon: 'cards/conteudo-3.svg',
      },
      {
        id: 5,
        title: 'Árvore Livros',
        description: 'Biblioteca de livros paradidáticos e romances',
        url: '#!',
        color: '#673AB7',
        icon: 'cards/conteudo-6.svg',
      },
    ],
  },
  {
    id: 2,
    title: 'Recursos',
    cards: [
      {
        id: 0,
        title: 'Plano Semanal',
        description:
          'Divisão do conteúdo em semanas e sugestões de conteúdos para alunos',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-1.svg',
      },
      {
        id: 1,
        title: 'Salas Virtuais',
        description: 'Ambiente para aulas online ao vivo',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-2.svg',
      },
      {
        id: 3,
        title: 'Word',
        description: 'Ferramenta de criação e edição de textos da Microsoft.',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-4.svg',
      },
      {
        id: 4,
        title: 'Excel',
        description:
          'Ferramenta de criação e edição de planilhas da Microsoft.',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-5.svg',
      },
      {
        id: 5,
        title: 'Power Point',
        description:
          'Ferramenta de criação e edição de slides de apresentação da Microsoft',
        url: '#!',
        color: '#9C27B0',
        icon: 'cards/recurso-6.svg',
      },
    ],
  },
  {
    id: 3,
    title: 'Comunicação',
    cards: [
      {
        id: 0,
        title: 'Mensagens',
        description: 'Ferramenta de mensagens entre professores, pais e alunos',
        url: '#!',
        color: '#03A9F4',
        icon: 'cards/comunicacao-1.svg',
      },
      {
        id: 1,
        title: 'Agenda',
        description: 'Agenda de eventos para a escola e professores',
        url: '#!',
        color: '#03A9F4',
        icon: 'cards/comunicacao-2.svg',
      },
    ],
  },
  {
    id: 4,
    title: 'Formação',
    cards: [
      {
        id: 0,
        title: 'Programa de Cursos 2020',
        description: 'Plataforma de formação continuada para professores',
        url: '#!',
        color: '#00BCD4',
        icon: 'cards/formacao-1.svg',
      },
      {
        id: 1,
        title: 'Proposta Pedagógica',
        description: 'Guias e documentos de apoio ao professor',
        url: '#!',
        color: '#00BCD4',
        icon: 'cards/formacao-2.svg',
      },
    ],
  },
];

const familia = [
  {
    id: 0,
    title: 'Avaliação',
    cards: [
      {
        id: 4,
        title: 'Relatórios',
        description: 'Relatórios de atividades e avaliações',
        url: '#!',
        color: '#3F51B5',
        icon: 'cards/avaliacao-5.svg',
      },
    ],
  },
  {
    id: 3,
    title: 'Comunicação',
    cards: [
      {
        id: 1,
        title: 'Agenda',
        description: 'Agenda de eventos para a escola e professores',
        url: '#!',
        color: '#03A9F4',
        icon: 'cards/comunicacao-2.svg',
      },
      {
        id: 2,
        title: 'Diário',
        description:
          'Ferramenta de comunicação entre escola e pais da Educação Infantil',
        url: '#!',
        color: '#03A9F4',
        icon: 'cards/comunicacao-3.svg',
      },
    ],
  },
];

export {
  professorMedio,
  professorEF2,
  professorEF1,
  professorInfantil,
  aluno,
  familia,
};
